
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3010:3010"
    environment:
      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_USERNAME: admin
      DB_PASSWORD: admin
      DB_NAME: library
      API_PORT: 3010
      DB_SYNCHRONIZE: false
      DB_LOGGING: false
      DB_RUN_MIGRATIONS: true
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  postgres-db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: library
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d library"]
      interval: 10s
      timeout: 5s
      retries: 2

networks:
  app-network:
    driver: bridge
